### ISSUE TITLE
“Sparse checkout leaves no entry on working directory” when fetching parent hub during build

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/jekyll-theme-open-project-helpers#12]
Known to have caused https://github.com/riboseinc/metanorma.com/issues/23#issuecomment-423455173.

```
bundler: failed to load command: jekyll (/Users/tony/.rvm/gems/ruby-2.4.4/bin/jekyll)
Git::GitExecuteError: git '--git-dir=/Volumes/Ribose/metanorma.com/parent-hub/.git' '--work-tree=/Volumes/Ribose/metanorma.com/parent-hub' checkout '--force' 'origin/master'  2>&1:error: Sparse checkout leaves no entry on working directory
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/git-1.5.0/lib/git/lib.rb:967:in `command'
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/git-1.5.0/lib/git/lib.rb:652:in `checkout'
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/git-1.5.0/lib/git/base.rb:306:in `checkout'
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-theme-open-project-helpers-1.0.6/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:191:in `git_shallow_checkout'                                 
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-theme-open-project-helpers-1.0.6/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:70:in `fetch_hub_logo'                                        
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-theme-open-project-helpers-1.0.6/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:62:in `read'                                                  
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-3.8.3/lib/jekyll/site.rb:164:in `read'
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-3.8.3/lib/jekyll/site.rb:69:in `process'
```

**Comment by strogonoff** [comment]
Should be fixed in af107b5
